FROM 190749975524.dkr.ecr.ap-northeast-1.amazonaws.com/nsb-stg-fe-user:nsb-base-user AS BUILD

WORKDIR /app

COPY . .
RUN yarn
RUN yarn build:stg 

# Install node-prune
RUN yarn global add node-prune 
RUN node-prune

# Run image 
FROM 190749975524.dkr.ecr.ap-northeast-1.amazonaws.com/nsb-stg-fe-user:nsb-base-user AS PRODUCTION

WORKDIR /app

COPY --from=BUILD /app/package.json /app/yarn.lock /app/next-i18next.config.js /app/next.config.js ./
COPY --from=BUILD /app/node_modules ./node_modules
COPY --from=BUILD /app/.next ./.next
COPY --from=BUILD /app/public ./public


CMD ["yarn", "preview"]
