export const FIREBASE = {
  BET_SETTING: 'BET_SETTING',
  T_BET_USER: 'T_BET_USER',
  USER: 'USER',
  DEV: 'DEV',
  TOTAL_TICKET_BET_SETTING_ID: 'TOTAL_TICKET_BET_SETTING_ID',
  TOTAL_TICKET_AND_BALANCE_USER: 'TOTAL_TICKET_AND_BALANCE_USER',
  ID: 'ID',
  SPONSOR: 'SPONSOR',
  SPONSOR_PRICE: 'SPONSOR_PRICE',
  MATCH: 'MATCH',
  MATCH_ID: 'MATCH_ID',
  TOURNAMENT_ID: 'TOURNAMENT_ID',
  MATCH_GLOBAL_ID: 'MATCH_GLOBAL_ID',
  TOURNAMENT_GLOBAL_ID: 'TOURNAMENT_GLOBAL_ID',
  TOTAL_TICKET_MATCH_NORMAL_ID: 'TOTAL_TICKET_MATCH_NORMAL_ID'
}
